version: "1.0"

services:
  - name: thinkchessy
    type: web
    build:
      dockerfilePath: Dockerfile
    source:
      type: git
      repo_url: https://github.com/Aryan12x/koyebA2.git
      branch: main
    env:
      - name: TELEGRAM_BOT_TOKEN
        value: "<your_bot_token>"
    ports:
      - port: 8080
    scale:
      min: 1
      max: 1

